name: 'Pull Request'

on: ['pull_request']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      # cached yarn install
      - uses: bahmutov/npm-install@v1
      - name: Run tests
        run: yarn test:ci
      - name: Visual tests
        run: yarn test:e2e
      - name: Create test report
        if: always()
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  styleguide:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      # cached yarn install
      - uses: bahmutov/npm-install@v1
      - run: yarn styleguide:build
      - name: Uploading styleguide artifact
        uses: actions/upload-artifact@v2
        with:
          name: styleguide
          path: docs/
